/**
 * 관세청 "해외직구물품 예상세액 조회" 공식 계산기의 품목·세율 데이터.
 *
 * https://www.customs.go.kr/kcs/ad/tax/BuyTaxCalculation.do 의 클라이언트
 * 스크립트(js/common/buyTax.js, 2026-07-25 확인)에서 그대로 추출했습니다.
 * 품목 137개, 관세율 68개 항목을 5개 계산 케이스(관세율표 kind1 vs kind5
 * 등)로 실제 라이브 계산기와 대조 검증했으며, 원 단위까지 정확히 일치함을
 * 확인했습니다(자동 추출 스크립트가 item 30(위스키)의 FTA 세율을 놓친
 * 버그를 소스 직접 대조로 발견해 수정함 — 자동 추출 결과를 맹신하지 않고
 * 반드시 원문과 재대조할 것).
 *
 * itemKind: 1=기본관세, 4=한·EU FTA, 5=한·미 FTA. (원본에 존재하는 2=양허관세,
 * 3=협력관세는 실제 배포된 페이지의 드롭다운에서 선택 불가능한 죽은 코드라
 * 제외했습니다 — 배포 페이지의 itemKind <select>는 1/4/5만 제공합니다.)
 *
 * 세율표에 명시적 항목이 없는 (품목,kind) 조합은 원본의 기본값 규칙을
 * 따릅니다: kind가 4 또는 5(FTA)면 0%, 그 외(kind=1, 기본관세)면 8%.
 * (`getTariffRate` 참고)
 *
 * 📋 법령 현황 추적: 프로젝트 루트 LEGAL_REFERENCES.md →
 *    "생활 > 관부가세 계산기". 관세청이 buyTax.js를 갱신하면 이 파일도
 *    재추출해 갱신하세요.
 */

export const CUSTOMS_ITEMS_DATA = [
  { id: 1, category: '식품/의약품', name: "볶은커피" },
  { id: 2, category: '식품/의약품', name: "인스턴트커피" },
  { id: 3, category: '식품/의약품', name: "인스턴트 커피믹스" },
  { id: 4, category: '식품/의약품', name: "녹차" },
  { id: 5, category: '식품/의약품', name: "홍차" },
  { id: 6, category: '식품/의약품', name: "조제차 티백" },
  { id: 7, category: '식품/의약품', name: "기타차" },
  { id: 8, category: '식품/의약품', name: "버진올리브유" },
  { id: 109, category: '식품/의약품', name: "혼합양념소스" },
  { id: 110, category: '식품/의약품', name: "케첩" },
  { id: 28, category: '식품/의약품', name: "로열젤리, 벌꿀조제품" },
  { id: 17, category: '식품/의약품', name: "캔디류" },
  { id: 18, category: '식품/의약품', name: "코코아 가루(무가당)" },
  { id: 19, category: '식품/의약품', name: "코코아 가루(가당)" },
  { id: 20, category: '식품/의약품', name: "초콜릿과 초콜릿과자" },
  { id: 116, category: '식품/의약품', name: "비스킷,쿠키,크레커" },
  { id: 117, category: '식품/의약품', name: "콘 플레이크" },
  { id: 118, category: '식품/의약품', name: "오트밀" },
  { id: 119, category: '식품/의약품', name: "인조꿀" },
  { id: 120, category: '식품/의약품', name: "시럽" },
  { id: 121, category: '식품/의약품', name: "잼, 과일젤리" },
  { id: 123, category: '식품/의약품', name: "피넛버터" },
  { id: 124, category: '식품/의약품', name: "씨리얼" },
  { id: 125, category: '식품/의약품', name: "라면, 파스타면" },
  { id: 29, category: '식품/의약품', name: "와인" },
  { id: 30, category: '식품/의약품', name: "위스키" },
  { id: 128, category: '식품/의약품', name: "사케" },
  { id: 129, category: '식품/의약품', name: "브랜디" },
  { id: 23, category: '식품/의약품', name: "건강기능식품" },
  { id: 25, category: '식품/의약품', name: "오메가-3 제품" },
  { id: 26, category: '식품/의약품', name: "클로렐라,스피루리나 제품" },
  { id: 133, category: '식품/의약품', name: "단백질보충제" },
  { id: 134, category: '식품/의약품', name: "반창고, 거즈" },
  { id: 13, category: '유아/장난감', name: "조제분유" },
  { id: 11, category: '유아/장난감', name: "육류이유식" },
  { id: 12, category: '유아/장난감', name: "채소이유식" },
  { id: 14, category: '유아/장난감', name: "일회용기저귀" },
  { id: 9, category: '유아/장난감', name: "유아용화장품" },
  { id: 140, category: '유아/장난감', name: "유아용의류" },
  { id: 141, category: '유아/장난감', name: "유아용냅킨" },
  { id: 15, category: '유아/장난감', name: "유모차, 부분품" },
  { id: 16, category: '유아/장난감', name: "유아용 보행기" },
  { id: 46, category: '유아/장난감', name: "완구(장난감)" },
  { id: 145, category: '유아/장난감', name: "피규어" },
  { id: 146, category: '유아/장난감', name: "블록, 보드게임, 퍼즐" },
  { id: 148, category: '유아/장난감', name: "RC카" },
  { id: 149, category: '화장실/미용/생활/욕실', name: "카시트" },
  { id: 34, category: '화장실/미용/생활/욕실', name: "기초화장용제품" },
  { id: 151, category: '화장실/미용/생활/욕실', name: "선크림" },
  { id: 152, category: '화장실/미용/생활/욕실', name: "마스크팩" },
  { id: 33, category: '화장실/미용/생활/욕실', name: "페이스파우더" },
  { id: 35, category: '화장실/미용/생활/욕실', name: "메이크업용 제품" },
  { id: 155, category: '화장실/미용/생활/욕실', name: "화장용티슈" },
  { id: 32, category: '화장실/미용/생활/욕실', name: "입술화장용제품" },
  { id: 31, category: '화장실/미용/생활/욕실', name: "향수" },
  { id: 158, category: '화장실/미용/생활/욕실', name: "클렌저" },
  { id: 10, category: '화장실/미용/생활/욕실', name: "목욕제품" },
  { id: 159, category: '화장실/미용/생활/욕실', name: "네일제품" },
  { id: 160, category: '화장실/미용/생활/욕실', name: "핸드크림" },
  { id: 36, category: '화장실/미용/생활/욕실', name: "샴푸,린스,헤어제품" },
  { id: 163, category: '화장실/미용/생활/욕실', name: "치약, 칫솔, 치실" },
  { id: 164, category: '화장실/미용/생활/욕실', name: "데오도란트" },
  { id: 165, category: '화장실/미용/생활/욕실', name: "점안액" },
  { id: 166, category: '화장실/미용/생활/욕실', name: "콘택트렌즈" },
  { id: 167, category: '화장실/미용/생활/욕실', name: "비누" },
  { id: 168, category: '화장실/미용/생활/욕실', name: "세탁세제, 주방세제" },
  { id: 169, category: '화장실/미용/생활/욕실', name: "수건" },
  { id: 39, category: '의류/패션잡화', name: "의류, 속옷" },
  { id: 40, category: '의류/패션잡화', name: "신발" },
  { id: 173, category: '의류/패션잡화', name: "양말, 스타킹, 레깅스" },
  { id: 175, category: '의류/패션잡화', name: "넥타이" },
  { id: 176, category: '의류/패션잡화', name: "스카프, 머플러" },
  { id: 177, category: '의류/패션잡화', name: "모자" },
  { id: 178, category: '의류/패션잡화', name: "우산" },
  { id: 179, category: '의류/패션잡화', name: "장갑" },
  { id: 180, category: '의류/패션잡화', name: "벨트" },
  { id: 181, category: '의류/패션잡화', name: "목걸이, 팔찌, 귀걸이" },
  { id: 182, category: '의류/패션잡화', name: "안경, 선글라스" },
  { id: 44, category: '의류/패션잡화', name: "고급손목시계" },
  { id: 45, category: '의류/패션잡화', name: "일반손목시계" },
  { id: 185, category: '의류/패션잡화', name: "시계밴드" },
  { id: 186, category: '의류/패션잡화', name: "캐리어" },
  { id: 37, category: '의류/패션잡화', name: "고급핸드백" },
  { id: 38, category: '의류/패션잡화', name: "일반핸드백" },
  { id: 189, category: '의류/패션잡화', name: "지갑, 카드지갑" },
  { id: 190, category: '의류/패션잡화', name: "핸드폰케이스" },
  { id: 191, category: '레저/스포츠', name: "스포츠의류" },
  { id: 192, category: '레저/스포츠', name: "스포츠신발" },
  { id: 193, category: '레저/스포츠', name: "글러브, 스포츠장갑" },
  { id: 194, category: '레저/스포츠', name: "수영복" },
  { id: 195, category: '레저/스포츠', name: "수영고글" },
  { id: 196, category: '레저/스포츠', name: "골프용품" },
  { id: 197, category: '레저/스포츠', name: "낚시용품" },
  { id: 198, category: '레저/스포츠', name: "공" },
  { id: 199, category: '레저/스포츠', name: "자전거, 자전거 용품" },
  { id: 200, category: '레저/스포츠', name: "라켓" },
  { id: 201, category: '레저/스포츠', name: "스키, 보드용품" },
  { id: 202, category: '레저/스포츠', name: "텐트" },
  { id: 203, category: '가구/인테리어/침구', name: "가구" },
  { id: 208, category: '가구/인테리어/침구', name: "매트리스" },
  { id: 209, category: '가구/인테리어/침구', name: "침대시트, 커버" },
  { id: 210, category: '가구/인테리어/침구', name: "이불" },
  { id: 211, category: '가구/인테리어/침구', name: "침낭" },
  { id: 212, category: '가구/인테리어/침구', name: "커튼" },
  { id: 213, category: '가구/인테리어/침구', name: "베개, 쿠션" },
  { id: 216, category: '가구/인테리어/침구', name: "테이블매트" },
  { id: 217, category: '가구/인테리어/침구', name: "조명" },
  { id: 218, category: '주방', name: "식기, 주방용품" },
  { id: 221, category: '주방', name: "포크, 나이프" },
  { id: 222, category: '주방', name: "텀블러" },
  { id: 223, category: '컴퓨터/가전/영상/음향', name: "컴퓨터, 관련 부품" },
  { id: 41, category: '컴퓨터/가전/영상/음향', name: "노트북" },
  { id: 226, category: '컴퓨터/가전/영상/음향', name: "모니터" },
  { id: 227, category: '컴퓨터/가전/영상/음향', name: "키보드" },
  { id: 228, category: '컴퓨터/가전/영상/음향', name: "마우스" },
  { id: 229, category: '컴퓨터/가전/영상/음향', name: "프린터" },
  { id: 230, category: '컴퓨터/가전/영상/음향', name: "스캐너" },
  { id: 231, category: '컴퓨터/가전/영상/음향', name: "스마트폰" },
  { id: 232, category: '컴퓨터/가전/영상/음향', name: "스마트워치" },
  { id: 233, category: '컴퓨터/가전/영상/음향', name: "보조배터리" },
  { id: 43, category: '컴퓨터/가전/영상/음향', name: "디지털TV" },
  { id: 235, category: '컴퓨터/가전/영상/음향', name: "디지털카메라" },
  { id: 236, category: '컴퓨터/가전/영상/음향', name: "카메라부분품" },
  { id: 237, category: '컴퓨터/가전/영상/음향', name: "캠코더" },
  { id: 238, category: '컴퓨터/가전/영상/음향', name: "진공청소기" },
  { id: 239, category: '컴퓨터/가전/영상/음향', name: "가습기" },
  { id: 240, category: '컴퓨터/가전/영상/음향', name: "전자담배" },
  { id: 241, category: '컴퓨터/가전/영상/음향', name: "헤어드라이어" },
  { id: 242, category: '컴퓨터/가전/영상/음향', name: "전기면도기" },
  { id: 243, category: '컴퓨터/가전/영상/음향', name: "미용기기" },
  { id: 244, category: '컴퓨터/가전/영상/음향', name: "오디오" },
  { id: 245, category: '컴퓨터/가전/영상/음향', name: "헤드셋, 이어폰" },
  { id: 246, category: '컴퓨터/가전/영상/음향', name: "스피커" },
  { id: 247, category: '컴퓨터/가전/영상/음향', name: "마이크" },
  { id: 248, category: '도서', name: "서적, 잡지류" },
  { id: 249, category: '도서', name: "공 CD, DVD" },
  { id: 250, category: '도서', name: "CD, DVD 음반" },
];

export const TARIFF_RATE_TABLE_DATA: Record<number, Partial<Record<1 | 4 | 5, number>>> = {
  1: { 1: 8 },
  2: { 1: 8 },
  3: { 1: 8 },
  4: { 1: 40, 4: 162.1, 5: 68.4 },
  5: { 1: 40 },
  6: { 1: 40 },
  7: { 1: 40 },
  8: { 1: 5 },
  9: { 1: 8 },
  10: { 1: 8 },
  11: { 1: 18 },
  12: { 1: 18 },
  13: { 1: 36 },
  14: { 1: 8 },
  15: { 1: 5 },
  16: { 1: 8 },
  17: { 1: 8 },
  18: { 1: 5 },
  19: { 1: 8 },
  20: { 1: 8 },
  23: { 1: 8 },
  25: { 1: 8 },
  26: { 1: 8 },
  28: { 1: 8 },
  29: { 1: 30, 4: 0, 5: 0 },
  30: { 1: 30, 4: 0, 5: 0 },
  31: { 1: 8, 4: 0, 5: 0 },
  32: { 1: 8, 4: 0, 5: 0 },
  33: { 1: 8, 4: 0, 5: 0 },
  34: { 1: 8, 4: 0, 5: 0 },
  35: { 1: 8, 4: 0, 5: 0 },
  36: { 1: 5, 4: 0, 5: 0 },
  37: { 1: 8, 4: 0, 5: 0 },
  38: { 1: 8, 4: 0, 5: 0 },
  39: { 1: 13, 4: 0, 5: 0 },
  40: { 1: 13, 4: 0, 5: 0 },
  41: { 1: 8, 5: 0 },
  43: { 1: 8, 5: 0 },
  44: { 1: 8, 4: 0, 5: 0 },
  45: { 1: 8, 4: 0, 5: 0 },
  46: { 1: 8, 5: 0 },
  109: { 1: 8, 4: 8.4, 5: 6 },
  116: { 1: 5 },
  117: { 1: 5.4 },
  118: { 1: 8 },
  119: { 1: 20 },
  121: { 1: 30 },
  123: { 1: 50 },
  124: { 1: 5 },
  125: { 1: 5 },
  128: { 1: 30 },
  129: { 1: 30 },
  169: { 1: 13 },
  173: { 1: 13 },
  178: { 1: 13 },
  180: { 1: 13 },
  191: { 1: 13 },
  192: { 1: 13 },
  193: { 1: 13 },
  194: { 1: 13 },
  202: { 1: 13 },
  209: { 1: 10 },
  212: { 1: 13 },
  216: { 1: 13 },
  223: { 1: 8 },
  235: { 1: 0 },
  248: { 1: 0 },
  249: { 1: 0 },
};

export const CONSUMPTION_TAX_RATE_DATA: Record<number, number> = {
  37: 20,
  44: 20,
};

export const EDUCATION_TAX_RATE_DATA: Record<number, number> = {
  29: 10,
  30: 30,
  37: 30,
  44: 30,
  128: 10,
  129: 30,
};

export const AGRICULTURE_TAX_RATE_DATA: Record<number, number> = {
  31: 10,
};

export const LIQUOR_TAX_RATE_DATA: Record<number, number> = {
  29: 30,
  30: 72,
  128: 30,
  129: 72,
};
